version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${YGGDRASIL_POSTGRES_USER}
      - POSTGRES_PASSWORD=${YGGDRASIL_POSTGRES_PASSWORD}
      - POSTGRES_DB=${YGGDRASIL_POSTGRES_DB}
    ports:
      - "${YGGDRASIL_POSTGRES_PORT-5432}:5432"
